version: "3"

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.1
    ports:
      - 7700:7700
    volumes:
      - ms_data:/data.ms

volumes:
  ms_data:
      driver: local